/**
 * High-frequency Japanese glosses (short-term patch before JMdict).
 * Keys are usually dictionary forms (lemma); surface overrides handle inflections.
 */
export const COMMON_LEMMA_MEANINGS: Record<string, string> = {
  // Pronouns & people
  私: "I / me",
  僕: "I (male)",
  彼: "he",
  彼女: "she",
  友達: "friend",
  人: "person / people",
  先生: "teacher",
  学生: "student",
  子供: "child",
  家族: "family",

  // Time
  今日: "today",
  昨日: "yesterday",
  明日: "tomorrow",
  今: "now",
  朝: "morning",
  昼: "noon / daytime",
  夜: "night / evening",
  夕方: "evening",
  先週: "last week",
  今週: "this week",
  来週: "next week",
  月: "month / moon",
  年: "year",
  時: "hour / time",
  分: "minute",
  一日: "one day / all day",

  // Places
  学校: "school",
  家: "home / house",
  公園: "park",
  図書館: "library",
  駅: "station",
  店: "shop / store",
  日本: "Japan",
  国: "country",

  // Food
  ご飯: "meal / rice",
  御飯: "meal / rice",
  朝ごはん: "breakfast",
  昼ご飯: "lunch",
  昼ごはん: "lunch",
  晩ごはん: "dinner",
  弁当: "boxed lunch / bento",
  お弁当: "boxed lunch / bento",
  水: "water",
  お茶: "tea",
  コーヒー: "coffee",
  パン: "bread",
  ミルク: "milk",
  肉: "meat",
  魚: "fish",
  野菜: "vegetable",
  果物: "fruit",
  おにぎり: "rice ball",

  // Nature & weather
  天気: "weather",
  空: "sky",
  雨: "rain",
  雪: "snow",
  風: "wind",
  桜: "cherry blossom",
  木: "tree",
  花: "flower",
  川: "river",
  山: "mountain",
  海: "sea",

  // Common nouns
  本: "book",
  車: "car",
  電車: "train",
  道: "road / way",
  名前: "name",
  仕事: "work / job",
  勉強: "study",
  話: "story / talk",
  言葉: "word / language",
  意味: "meaning",
  問題: "problem / question",
  答え: "answer",
  一緒: "together",
  みんな: "everyone",
  物: "thing",
  事: "matter / thing",
  所: "place",
  下: "under / below",
  上: "above / on",
  中: "inside / middle",
  外: "outside",
  前: "front / before",
  後: "after / behind",
  近く: "nearby",
  隣: "next to",

  // Verbs (dictionary form)
  行く: "go",
  来る: "come",
  帰る: "return home",
  食べる: "eat",
  飲む: "drink",
  見る: "see / look",
  聞く: "hear / listen / ask",
  読む: "read",
  書く: "write",
  話す: "speak / talk",
  言う: "say",
  思う: "think",
  知る: "know",
  分かる: "understand",
  勉強する: "study",
  働く: "work",
  買う: "buy",
  売る: "sell",
  作る: "make",
  使う: "use",
  持つ: "hold / have",
  待つ: "wait",
  会う: "meet",
  教える: "teach",
  習う: "learn",
  起きる: "wake up",
  寝る: "sleep",
  入る: "enter",
  出る: "leave / go out",
  着る: "wear",
  脱ぐ: "take off (clothes)",
  洗う: "wash",
  走る: "run",
  歩く: "walk",
  泳ぐ: "swim",
  遊ぶ: "play",
  散歩する: "take a walk",
  座る: "sit",
  立つ: "stand",
  開ける: "open",
  閉める: "close",
  始める: "start",
  終わる: "end / finish",
  住む: "live (reside)",
  欲しい: "want",
  いる: "be / exist (animate)",
  ある: "be / exist (inanimate)",
  する: "do",

  // Adjectives
  いい: "good",
  良い: "good",
  悪い: "bad",
  大きい: "big",
  小さい: "small",
  新しい: "new",
  古い: "old",
  高い: "high / expensive",
  安い: "cheap",
  暑い: "hot (weather)",
  寒い: "cold (weather)",
  熱い: "hot (thing)",
  冷たい: "cold (thing)",
  忙しい: "busy",
  暇: "free time",
  楽しい: "fun / enjoyable",
  面白い: "interesting",
  つまらない: "boring",
  難しい: "difficult",
  易しい: "easy",
  優しい: "kind",
  きれい: "pretty / clean",
  静か: "quiet",
  元気: "healthy / energetic",
  有名: "famous",
  便利: "convenient",
  不便: "inconvenient",
  好き: "like",
  嫌い: "dislike",
  上手: "skillful",
  下手: "unskillful",
  同じ: "same",
  違う: "different",
  青い: "blue",
  赤い: "red",
  白い: "white",
  黒い: "black",
  おいしい: "delicious",

  // Adverbs & misc
  とても: "very",
  少し: "a little",
  もう: "already",
  まだ: "still / not yet",
  よく: "often / well",
  あまり: "not very",
  いつも: "always",
  時々: "sometimes",
  たくさん: "many / a lot",
  すぐ: "soon / immediately",
  ゆっくり: "slowly",
  一緒に: "together",
  まず: "first",
  それから: "then / after that",
  でも: "but / however",
  だから: "therefore",
  ここ: "here",
  そこ: "there",
  あそこ: "over there",
  どこ: "where",
  何: "what",
  誰: "who",
  いつ: "when",
  どう: "how",
  どうして: "why",
  どれ: "which",
  これ: "this",
  それ: "that",
  あれ: "that (over there)",

  // Copula & auxiliaries (grammar glosses for popups)
  です: "is / am / are (polite)",
  だ: "is / am / are (plain)",
  ます: "polite form",
  た: "past tense",
  ない: "negative",
  れる: "passive / potential",
  られる: "passive / potential",
};

/** Surface forms that should not fall through to lemma alone. */
export const COMMON_SURFACE_MEANINGS: Record<string, string> = {
  ご飯: "meal / rice",
  御飯: "meal / rice",
  友だち: "friend",
  一緒に: "together",
  食べ: "eat",
  飲み: "drink",
  行き: "go",
  来: "come",
  見: "see",
  読み: "read",
  書き: "write",
  話し: "speak",
  持っ: "hold / bring",
  作っ: "make",
  洗い: "wash",
  起き: "wake up",
  寝: "sleep",
  帰: "return",
  会: "meet",
  買: "buy",
  売: "sell",
  使: "use",
  待: "wait",
  走: "run",
  歩: "walk",
  座: "sit",
  立: "stand",
  開: "open",
  閉: "close",
  始: "start",
  終わ: "finish",
  まし: "polite form",
  ませ: "polite form",
  でし: "polite copula",
  くて: "te-form (and)",
  かった: "past (adjective)",
  く: "adverbial form",
};
